### ISSUE TITLE
Add CI support to the CMake version of FB experimental branch

### ISSUE THREAD

**Issue by mike-myers-tob** [osql/osql#2]
@Smjert wrote:

> The current idea is to use [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) (free?), which works similar to Travis.
> 
> If we want to use Azure, we need to write a YAML file with the configuration and push it to the branches we want to build and also give the Azure app access to the repository.

**Comment by Smjert** [comment]
First developments: the CI is up, [here](https://dev.azure.com/trailofbits/osql/_build?definitionId=1) the status of the first two builds on master and development.

Next: 
- [ ] Some tests require to be run as root, change the call to ctest
- [ ] Add status badges for build and tests on master and development to the README
- [ ] Show more verbose tests output, some test seems to be wrongly skipped but marked as passed.

Since I forgot to mention this issue, here a couple of related commits: https://github.com/osql/osql/commit/c0dad1a4fdfb21b7242359c8014734f980589569 https://github.com/osql/osql/commit/a33ee3f893acde1be0037e47e83b9403e8d66aa6

**Comment by Smjert** [comment]
I will close the issue for now, since it's complete.

Running tests with root is not currently feasible due to how tests are structured and not separated between the ones that need it and the ones that do not.
The result is that some tests that do not require root access actually fail because they expect to be run with a normal user.
